### ISSUE TITLE
Add OpenSSH to installed package

### ISSUE THREAD

**Issue by philipmat** [William-Yeh/docker-ansible#18]
This would allow reusable connections (`-c ssh`).

Might also need the [sshpass](http://linux.die.net/man/1/sshpass) package until this [pull request is accepted](https://github.com/ansible/ansible/pull/14034).

**Comment by William-Yeh** [comment]
Similar to https://github.com/William-Yeh/docker-ansible/issues/14

At first, I designed these series of images according to the best practice of Docker: [If you run SSHD in your Docker containers, you're doing it wrong!](https://jpetazzo.github.io/2014/06/23/docker-ssh-considered-evil/) So I didn't try to touch any SSH stuff unless absolutely necessary.

So, I prefer installing such stuff at derived images or by another script (maybe `install-openssh.sh`?).

**Comment by philipmat** [comment]
Sorry if I wasn't clear. I'm not talking about the ssh _daemon_, but the ssh _client_ libraries. This allows Ansible to use OpenSSH libraries over paramiko:

> In Ansible 1.2.1 and later, ‘ssh’ will be used by default if OpenSSH is new enough to support ControlPersist as an option.
> Paramiko is great for starting out, but the OpenSSH type offers many advanced options.

https://support.ansible.com/hc/en-us/articles/201957917-How-do-I-get-ansible-to-reuse-connections-enable-Kerberized-SSH-or-have-Ansible-pay-attention-to-my-local-SSH-config-file-

**Comment by William-Yeh** [comment]
Now openssh-client/clients and sshpass are installed on all images, excluding the images with `-onbuild` and `mini-` tags.
