### ISSUE TITLE
Ansible for Alpine Linux 

### ISSUE THREAD

**Issue by hrstoyanov** [William-Yeh/docker-ansible#2]
William,
I like this docker images! Would it be possible to create Ansible image on top of Alpine Linux?
Alpine Linux is only 5MB and is becoming very popular for cloud deployment, would be awesome to have a reliable docker image ...

See : https://github.com/gliderlabs/docker-alpine

**Comment by William-Yeh** [comment]
@hrstoyanov Which Python runtime would you recommend for Alpine Linux?

I've found some candidates from http://yasermartinez.com/blog/posts/creating-super-small-docker-images.html but don't know which one is appropriate as a starting point.

**Comment by hrstoyanov** [comment]
William,
Thanks for booking into that ... I honestly not very good with Python. I
would suggest to go to: pkgs.alpinelinux.org They use a package manager APK
with lots of standard packages, one of which is Python 2.x

/Hristo Stoyanov

**Comment by William-Yeh** [comment]
Hi hrstoyanov,

I've made two images for Alpine 3: `williamyeh/alpine3` and `williamyeh/alpine3-onbuild`.

Please check if everything is OK.
