### ISSUE TITLE
Latest image 4b2f46c13c6d of williamyeh/ansible:ubuntu14.04-onbuild causes regression in our playbook

### ISSUE THREAD

**Issue by chrisheaththomas** [William-Yeh/docker-ansible#23]
Step 3 : RUN ansible-playbook-wrapper
 ---> Running in e39c3d9048c3

PLAY [127.0.0.1] ***************************************************************
skipping: no hosts matched

Previous image 35bc5a1b25d6 works for us.

Currently using  master-ubuntu14.04-onbuild as workaround.

**Comment by William-Yeh** [comment]
Hi,

I couldn't reproduce the error condition you've mentioned.
Would you provide the playbook and Dockerfile which can reproduce the error?

My test seems ok: https://asciinema.org/a/83884
