### ISSUE TITLE
No rsync in ansible:alpine3

### ISSUE THREAD

**Issue by rdavaillaud** [William-Yeh/docker-ansible#24]
Hello,
I have a playbook with a basic `synchronize` command.
Executing this playbook on a docker ansible:alpine3 container gives me this error:

```
fatal: [hbsded001]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find required executable rsync"}
```

Is this per-design or rsync is really missing? Can you add it to the image?

Thank you

**Comment by William-Yeh** [comment]
The Ansible [`synchronize` module](http://docs.ansible.com/ansible/synchronize_module.html) suggests,  "rsync must be installed on both the local and remote host." 

It seems that the original Alpine distributions (e.g., the [`maier/alpine-3.4-x86_64`](https://atlas.hashicorp.com/maier/boxes/alpine-3.4-x86_64) Vagrant box) do not have `rsync` pre-installed. For convenience, I'd like to pre-install `rsync` in `williamyeh/ansible:alpine3` and `williamyeh/ansible:1.9-alpine3`. Please wait several hours for Docker Hub to automate build them.

**Comment by lchabert** [comment]
Hi,

We have the same issue on Centos 7 image. Centos does not have rsync install by default.
Could you please make the same for centos7 image ?

Thanks.

**Comment by phillbaker** [comment]
@William-Yeh sorry for commenting on such an old issue, but given this issue and https://github.com/William-Yeh/docker-ansible/pull/27 would you accept a PR to add rsync to most images as a commonly used dependency (similar to git)?

**Comment by William-Yeh** [comment]
Added since 2016:
https://github.com/William-Yeh/docker-ansible/blob/7d885c87026bc44450b79f504b9a5becf0969783/alpine3/Dockerfile
