### ISSUE TITLE
Offer distinct Ansible versions

### ISSUE THREAD

**Issue by fiunchinho** [William-Yeh/docker-ansible#25]
This is a nice repository, but I miss the ability to choose between different Ansible versions, so test playbooks against different Ansible versions would be really easy.
I'd keep at least a different image for every minor version, like 1.9, 2.0, 2.1, and so on.

**Comment by Mehonoshin** [comment]
@fiunchinho I've added 2.2 version #26

**Comment by fiunchinho** [comment]
Nice! Any chance to add other versions like 2.0 or 2.1?

**Comment by Mehonoshin** [comment]
@fiunchinho waiting for maintainers response, if he does not mind, I'll add other minor versions
