### ISSUE TITLE
release frequencies?

### ISSUE THREAD

**Issue by hrstoyanov** [William-Yeh/docker-ansible#3]
William,
What is the release frequency for this image?
It seems like it is currently at Ansible 1.9.2, while Ansible official release is 1.9.3.1 as of today.

**Comment by William-Yeh** [comment]
Hi @hrstoyanov ,

I don't pin any specific Ansible version in the Dockerfiles.

These images are configured under the _automated build_ mechanism in Docker Hub, triggered by one of the following events:
1. Any new commits to GitHub.
2. Any new update from upstream base images ("Linked Docker Hub Repos" in Docker Hub web console).
3. Manually click the "Trigger a Build" button by me.

Personally I use `brew update; brew upgrade --all` on my Mac everyday. Maybe when I know any new reliable updates to Ansible, I'll click the "Trigger a Build" button on Docker Hub.  :)
