### ISSUE TITLE
Add cryptography library for ansible-vault

### ISSUE THREAD

**Issue by alexandrebodin** [William-Yeh/docker-ansible#36]
Hi,

I really need to be able to run ansible-vault command from the container but I get an error because it's missing the cryptography dependency.

Would be great to add it

Thanks a lot !

**Comment by jeantil** [comment]
@alexandrebodin I just encountered the same error, can you tell me how you solved this issue ?

**Comment by alexandrebodin** [comment]
Hi,

I created a custom DOCKERFILE  and install the lib I needed :)

**Comment by jeantil** [comment]
Thanks, I ended up copy pasting the original docker file and modified it to suit my needs too :)
