### ISSUE TITLE
error updating /etc/hosts file on cenotos7

### ISSUE THREAD

**Issue by DerManoMann** [William-Yeh/docker-ansible#4]
Hi there,

I've been trying to run an ansible script on centos7. Any idea why that would be?
Or is the use of ansible limited in some way?

This is my setup:

```
FROM williamyeh/ansible:centos7

# general update
RUN yum -y update

ADD ./ /tmp/ansible

RUN ansible-playbook --sudo --connection=local -vvv -e restart=true -e scratch_build=false -e serial=10 -i /tmp/ansible/docker-nodes /tmp/ansible/site.yml
```

This is the error I get:

```
TASK: [node | generate hosts file] ********************************************
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000 && echo $HOME/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000']
<127.0.0.1> EXEC ['/bin/sh', '-c', u'rc=flag; [ -r /etc/hosts ] || rc=2; [ -f /etc/hosts ] || rc=1; [ -d /etc/hosts ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc} "/etc/hosts && exit 0; (python -c \'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();\nafile = open("\'/etc/hosts\'", "rb")\nbuf = afile.read(BLOCKSIZE)\nwhile len(buf) > 0:\n\thasher.update(buf)\n\tbuf = afile.read(BLOCKSIZE)\nafile.close()\nprint(hasher.hexdigest())\' 2>/dev/null) || (python -c \'import sha; BLOCKSIZE = 65536; hasher = sha.sha();\nafile = open("\'/etc/hosts\'", "rb")\nbuf = afile.read(BLOCKSIZE)\nwhile len(buf) > 0:\n\thasher.update(buf)\n\tbuf = afile.read(BLOCKSIZE)\nafile.close()\nprint(hasher.hexdigest())\' 2>/dev/null) || (echo \'0 \'/etc/hosts)']
<127.0.0.1> PUT /tmp/tmpce0XQc TO /root/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000/source
<127.0.0.1> PUT /tmp/tmp5F2W8p TO /root/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000/copy
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=xluifxkeyvhjkjvbfusnehjxzdipsqpp] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-xluifxkeyvhjkjvbfusnehjxzdipsqpp; LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000/copy; rm -rf /root/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000/ >/dev/null 2>&1'"'"''
failed: [127.0.0.1] => {"failed": true}
msg: Could not replace file: /root/.ansible/tmp/ansible-tmp-1444078648.91-266229075750000/source to /etc/hosts: [Errno 16] Device or resource busy

```

**Comment by William-Yeh** [comment]
Hi,

Don't know the content of your `docker-nodes` file.  It seems that there's something wrong with it.

Could you try the following simpler example, using only 2 files (`Dockerfile` and `site.yml`)?

**`site.yml`**:

``` yaml
- hosts: all
  tasks:
    - name: install Apache web server
      yum: name=httpd  update_cache=yes  state=present
```

**`Dockerfile`**:

``` dockerfile
FROM williamyeh/ansible:centos7

# general update
RUN yum -y update

ADD . /tmp/ansible

RUN ansible-playbook --sudo --connection=local -vvv  \
    /tmp/ansible/site.yml
```

**Comment by DerManoMann** [comment]
The docker-nodes file is quite simple:

```
[primary]
127.0.0.1 name=t1-docker mongodb_id=0 dc=local iptables=false

[nodes]

[backup]
```

This is a stripped down version of how the inventory is used _for real_. 
Your example works as expected. I am not surprised because there are some yum update tasks that get executed in my playbook before the failing template task that also do work.

**Comment by William-Yeh** [comment]
The `docker build .` works for me, even if I incorporate your docker-nodes file in Dockerfile:

``` dockerfile
FROM williamyeh/ansible:centos7

# general update
RUN yum -y update

ADD . /tmp/ansible

RUN ansible-playbook --sudo --connection=local -vvv  \
    -i /tmp/ansible/docker-nodes  \
    /tmp/ansible/site.yml
```

Could you give a more self-contained but minimal example to reproduce the failure you've encountered?

**Comment by DerManoMann** [comment]
Yup - it reallty is the template task (or whatever it is doing to update a local file)

site.yml:

```
- hosts: all
  tasks:
    - name: /etc/hosts template test
      template: src=/tmp/ansible/hosts.j2 dest=/etc/hosts
```

hosts.j2: just an empty file in the right place

**Comment by DerManoMann** [comment]
Ah, just remembered about this and did another experiment.

While the above template task fails, it will work if the dest file does not yet exist or is created within the Dockerfile.

Example:
site.yml

```
- hosts: all
  tasks:
    - name: /etc/hosts template test
      template: src=/tmp/ansible/hosts.j2 dest=/tmp/abc
```

Dockerfile:

```
...
RUN echo abc >/tmp/abc
RUN ansible-playbook --sudo --connection=local -vvv  \
    /tmp/ansible/site.yml
...
```

I do not know much about docker and how the intermediate container and stuff work, but it seems that the /etc/hosts file is locked for whatever reason

**Comment by DerManoMann** [comment]
Ah, just remembered about this and did another experiment.

While the above template task fails, it will work if the dest file does not yet exist or is created within the Dockerfile.

Example:
site.yml
````
- hosts: all
  tasks:
    - name: /etc/hosts template test
      template: src=/tmp/ansible/hosts.j2 dest=/tmp/abc
```
Dockerfile:
````
...
RUN echo abc >/tmp/abc
RUN ansible-playbook --sudo --connection=local -vvv  \
    /tmp/ansible/site.yml
...
````

I do not know much about docker and how the intermediate container and stuff work, but it seems that the /etc/hosts file is locked for whatever reason

**Comment by William-Yeh** [comment]
The `/etc/hosts` file is crucial for Docker's linking system. Therefore, in the Docker world, `/etc/hosts` should only be manipulated manually at the _image_ level, rather than the _container_ level.

See: 
1. http://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts
2. https://docs.docker.com/userguide/dockerlinks/

**Comment by DerManoMann** [comment]
Oh, man! Sorry for wasing your time and lots of thanks!
